@extends('front.app')
@section('content')
    <div class="title" data-aos="fade-up">
        <div class="titleText">Cookies Policy</div>
        <div class="borderTitle"></div>
    </div>
        <div class="infoWrap">
            <div class="infoText">
                <h3>Manual Handling Ireland - utilizes cookies for statistical data collection purposes.</h3> <br>
                These cookies do not spread viruses nor can they access your hard drive. The website employs Google Analytics, a service provided by Google, Inc. (Google). Google Analytics uses cookies, which are text files placed on your computer, to analyze user interaction with the site. The information generated by these cookies, including your IP address, is transmitted to and stored on Google's servers in the United States.
                <br><br>
                Google utilizes this data to assess website usage, compile reports on website activity for operators, and offer additional services related to internet usage and website activity. Google may share this information with third parties when required by law or when these parties process data on Google's behalf. Your IP address will not be associated with any other data held by Google.
                <br><br>
                Google utilizes this data to assess website usage, compile reports on website activity for operators, and offer additional services related to internet usage and website activity. Google may share this information with third parties when required by law or when these parties process data on Google's behalf. Your IP address will not be associated with any other data held by Google.
            </div>
        </div>
    </div>
@endsection
